# Generated by Django 4.0.6 on 2022-08-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('customer_uuid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='user-img/')),
                ('birth', models.DateField(default=datetime.datetime(2022, 8, 8, 19, 41, 0, 255952))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
